# Generated by Django 3.2.4 on 2021-06-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_orderitem_review_shippingaddres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddres',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveredAd',
            new_name='deliveredAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paitAd',
            new_name='paidAt',
        ),
    ]
